# Generated by Django 3.2.18 on 2023-03-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_highlightsadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_path',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
