# Generated by Django 3.2.18 on 2023-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230320_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='User',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likes',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='User',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collaborators',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='User',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
